// Code generated by go-swagger; DO NOT EDIT.

package schedule

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

//go:generate mockery --name API --keeptree --with-expecter --case underscore

// API is the interface of the schedule client.
type API interface {
	/*
	   GetSchedulePaused gets scheduler paused status

	   Get scheduler paused status*/
	GetSchedulePaused(ctx context.Context, params *GetSchedulePausedParams) (*GetSchedulePausedOK, error)
	/*
	   ListSchedules lists schedules

	   List schedules*/
	ListSchedules(ctx context.Context, params *ListSchedulesParams) (*ListSchedulesOK, error)
}

// New creates a new schedule API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for schedule API
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
GetSchedulePaused gets scheduler paused status.

Get scheduler paused status.
*/
func (a *Client) GetSchedulePaused(ctx context.Context, params *GetSchedulePausedParams) (*GetSchedulePausedOK, error) {
	result, err := a.transport.SubmitContext(ctx, &runtime.ClientOperation{
		ID:                 "getSchedulePaused",
		Method:             "GET",
		PathPattern:        "/schedules/{job_type}/paused",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetSchedulePausedReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}

	switch value := result.(type) {
	case *GetSchedulePausedOK:
		return value, nil
	case *GetSchedulePausedBadRequest:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *GetSchedulePausedUnauthorized:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *GetSchedulePausedInternalServerError:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	}

	// unexpected response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown responses return an error above: so this is a codegen issue.
	msg := fmt.Sprintf("unexpected success response for getSchedulePaused: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ListSchedules lists schedules.

List schedules.
*/
func (a *Client) ListSchedules(ctx context.Context, params *ListSchedulesParams) (*ListSchedulesOK, error) {
	result, err := a.transport.SubmitContext(ctx, &runtime.ClientOperation{
		ID:                 "listSchedules",
		Method:             "GET",
		PathPattern:        "/schedules",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListSchedulesReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}

	switch value := result.(type) {
	case *ListSchedulesOK:
		return value, nil
	case *ListSchedulesBadRequest:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *ListSchedulesUnauthorized:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *ListSchedulesForbidden:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *ListSchedulesInternalServerError:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	}

	// unexpected response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown responses return an error above: so this is a codegen issue.
	msg := fmt.Sprintf("unexpected success response for listSchedules: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [ScheduleParams].
	ctx context.Context
}
