// Code generated by go-swagger; DO NOT EDIT.

package replication

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
	"github.com/goharbor/go-client/pkg/sdk/v2.0/models"
)

// ListReplicationPoliciesReader is a Reader for the ListReplicationPolicies structure.
type ListReplicationPoliciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListReplicationPoliciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListReplicationPoliciesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListReplicationPoliciesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListReplicationPoliciesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListReplicationPoliciesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /replication/policies] listReplicationPolicies", response, response.Code())
	}
}

// NewListReplicationPoliciesOK creates a ListReplicationPoliciesOK with default headers values
func NewListReplicationPoliciesOK() *ListReplicationPoliciesOK {
	return &ListReplicationPoliciesOK{}
}

/*
ListReplicationPoliciesOK describes a response with status code 200, with default header values.

Success
*/
type ListReplicationPoliciesOK struct {

	/* Link refers to the previous page and next page
	 */
	Link string

	/* The total count of the resources
	 */
	XTotalCount int64

	Payload []*models.ReplicationPolicy
}

// IsSuccess returns true when this list replication policies o k response has a 2xx status code
func (o *ListReplicationPoliciesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list replication policies o k response has a 3xx status code
func (o *ListReplicationPoliciesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list replication policies o k response has a 4xx status code
func (o *ListReplicationPoliciesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list replication policies o k response has a 5xx status code
func (o *ListReplicationPoliciesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list replication policies o k response a status code equal to that given
func (o *ListReplicationPoliciesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list replication policies o k response
func (o *ListReplicationPoliciesOK) Code() int {
	return 200
}

func (o *ListReplicationPoliciesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /replication/policies][%d] listReplicationPoliciesOK %s", 200, payload)
}

func (o *ListReplicationPoliciesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /replication/policies][%d] listReplicationPoliciesOK %s", 200, payload)
}

func (o *ListReplicationPoliciesOK) GetPayload() []*models.ReplicationPolicy {
	return o.Payload
}

func (o *ListReplicationPoliciesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Link
	hdrLink := response.GetHeader("Link")

	if hdrLink != "" {
		o.Link = hdrLink
	}

	// hydrates response header X-Total-Count
	hdrXTotalCount := response.GetHeader("X-Total-Count")

	if hdrXTotalCount != "" {
		valxTotalCount, err := conv.ConvertInt64(hdrXTotalCount)
		if err != nil {
			return errors.InvalidType("X-Total-Count", "header", "int64", hdrXTotalCount)
		}
		o.XTotalCount = valxTotalCount
	}

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListReplicationPoliciesUnauthorized creates a ListReplicationPoliciesUnauthorized with default headers values
func NewListReplicationPoliciesUnauthorized() *ListReplicationPoliciesUnauthorized {
	return &ListReplicationPoliciesUnauthorized{}
}

/*
ListReplicationPoliciesUnauthorized describes a response with status code 401, with default header values.

Unauthorized. Authentication is required to access this resource.
*/
type ListReplicationPoliciesUnauthorized struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this list replication policies unauthorized response has a 2xx status code
func (o *ListReplicationPoliciesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list replication policies unauthorized response has a 3xx status code
func (o *ListReplicationPoliciesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list replication policies unauthorized response has a 4xx status code
func (o *ListReplicationPoliciesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this list replication policies unauthorized response has a 5xx status code
func (o *ListReplicationPoliciesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this list replication policies unauthorized response a status code equal to that given
func (o *ListReplicationPoliciesUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the list replication policies unauthorized response
func (o *ListReplicationPoliciesUnauthorized) Code() int {
	return 401
}

func (o *ListReplicationPoliciesUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /replication/policies][%d] listReplicationPoliciesUnauthorized %s", 401, payload)
}

func (o *ListReplicationPoliciesUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /replication/policies][%d] listReplicationPoliciesUnauthorized %s", 401, payload)
}

func (o *ListReplicationPoliciesUnauthorized) GetPayload() *models.Errors {
	return o.Payload
}

func (o *ListReplicationPoliciesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListReplicationPoliciesForbidden creates a ListReplicationPoliciesForbidden with default headers values
func NewListReplicationPoliciesForbidden() *ListReplicationPoliciesForbidden {
	return &ListReplicationPoliciesForbidden{}
}

/*
ListReplicationPoliciesForbidden describes a response with status code 403, with default header values.

Forbidden. The caller does not have sufficient permission to perform the requested operation.
*/
type ListReplicationPoliciesForbidden struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this list replication policies forbidden response has a 2xx status code
func (o *ListReplicationPoliciesForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list replication policies forbidden response has a 3xx status code
func (o *ListReplicationPoliciesForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list replication policies forbidden response has a 4xx status code
func (o *ListReplicationPoliciesForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this list replication policies forbidden response has a 5xx status code
func (o *ListReplicationPoliciesForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this list replication policies forbidden response a status code equal to that given
func (o *ListReplicationPoliciesForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the list replication policies forbidden response
func (o *ListReplicationPoliciesForbidden) Code() int {
	return 403
}

func (o *ListReplicationPoliciesForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /replication/policies][%d] listReplicationPoliciesForbidden %s", 403, payload)
}

func (o *ListReplicationPoliciesForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /replication/policies][%d] listReplicationPoliciesForbidden %s", 403, payload)
}

func (o *ListReplicationPoliciesForbidden) GetPayload() *models.Errors {
	return o.Payload
}

func (o *ListReplicationPoliciesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListReplicationPoliciesInternalServerError creates a ListReplicationPoliciesInternalServerError with default headers values
func NewListReplicationPoliciesInternalServerError() *ListReplicationPoliciesInternalServerError {
	return &ListReplicationPoliciesInternalServerError{}
}

/*
ListReplicationPoliciesInternalServerError describes a response with status code 500, with default header values.

Internal server error. Inspect the `errors` array in the response body for details.
*/
type ListReplicationPoliciesInternalServerError struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this list replication policies internal server error response has a 2xx status code
func (o *ListReplicationPoliciesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list replication policies internal server error response has a 3xx status code
func (o *ListReplicationPoliciesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list replication policies internal server error response has a 4xx status code
func (o *ListReplicationPoliciesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list replication policies internal server error response has a 5xx status code
func (o *ListReplicationPoliciesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list replication policies internal server error response a status code equal to that given
func (o *ListReplicationPoliciesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list replication policies internal server error response
func (o *ListReplicationPoliciesInternalServerError) Code() int {
	return 500
}

func (o *ListReplicationPoliciesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /replication/policies][%d] listReplicationPoliciesInternalServerError %s", 500, payload)
}

func (o *ListReplicationPoliciesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /replication/policies][%d] listReplicationPoliciesInternalServerError %s", 500, payload)
}

func (o *ListReplicationPoliciesInternalServerError) GetPayload() *models.Errors {
	return o.Payload
}

func (o *ListReplicationPoliciesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
