// Code generated by go-swagger; DO NOT EDIT.

package project

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
	"github.com/goharbor/go-client/pkg/sdk/v2.0/models"
)

// ListArtifactsOfProjectReader is a Reader for the ListArtifactsOfProject structure.
type ListArtifactsOfProjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListArtifactsOfProjectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListArtifactsOfProjectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListArtifactsOfProjectBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewListArtifactsOfProjectUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListArtifactsOfProjectForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListArtifactsOfProjectNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewListArtifactsOfProjectUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListArtifactsOfProjectInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /projects/{project_name_or_id}/artifacts] listArtifactsOfProject", response, response.Code())
	}
}

// NewListArtifactsOfProjectOK creates a ListArtifactsOfProjectOK with default headers values
func NewListArtifactsOfProjectOK() *ListArtifactsOfProjectOK {
	return &ListArtifactsOfProjectOK{}
}

/*
ListArtifactsOfProjectOK describes a response with status code 200, with default header values.

Success
*/
type ListArtifactsOfProjectOK struct {

	/* Link refers to the previous page and next page
	 */
	Link string

	/* The total count of artifacts
	 */
	XTotalCount int64

	Payload []*models.Artifact
}

// IsSuccess returns true when this list artifacts of project o k response has a 2xx status code
func (o *ListArtifactsOfProjectOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list artifacts of project o k response has a 3xx status code
func (o *ListArtifactsOfProjectOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list artifacts of project o k response has a 4xx status code
func (o *ListArtifactsOfProjectOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list artifacts of project o k response has a 5xx status code
func (o *ListArtifactsOfProjectOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list artifacts of project o k response a status code equal to that given
func (o *ListArtifactsOfProjectOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list artifacts of project o k response
func (o *ListArtifactsOfProjectOK) Code() int {
	return 200
}

func (o *ListArtifactsOfProjectOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects/{project_name_or_id}/artifacts][%d] listArtifactsOfProjectOK %s", 200, payload)
}

func (o *ListArtifactsOfProjectOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects/{project_name_or_id}/artifacts][%d] listArtifactsOfProjectOK %s", 200, payload)
}

func (o *ListArtifactsOfProjectOK) GetPayload() []*models.Artifact {
	return o.Payload
}

func (o *ListArtifactsOfProjectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Link
	hdrLink := response.GetHeader("Link")

	if hdrLink != "" {
		o.Link = hdrLink
	}

	// hydrates response header X-Total-Count
	hdrXTotalCount := response.GetHeader("X-Total-Count")

	if hdrXTotalCount != "" {
		valxTotalCount, err := conv.ConvertInt64(hdrXTotalCount)
		if err != nil {
			return errors.InvalidType("X-Total-Count", "header", "int64", hdrXTotalCount)
		}
		o.XTotalCount = valxTotalCount
	}

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListArtifactsOfProjectBadRequest creates a ListArtifactsOfProjectBadRequest with default headers values
func NewListArtifactsOfProjectBadRequest() *ListArtifactsOfProjectBadRequest {
	return &ListArtifactsOfProjectBadRequest{}
}

/*
ListArtifactsOfProjectBadRequest describes a response with status code 400, with default header values.

Bad request. The request body or query parameters are invalid. Inspect the `errors` array in the response body for details.
*/
type ListArtifactsOfProjectBadRequest struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this list artifacts of project bad request response has a 2xx status code
func (o *ListArtifactsOfProjectBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list artifacts of project bad request response has a 3xx status code
func (o *ListArtifactsOfProjectBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list artifacts of project bad request response has a 4xx status code
func (o *ListArtifactsOfProjectBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list artifacts of project bad request response has a 5xx status code
func (o *ListArtifactsOfProjectBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list artifacts of project bad request response a status code equal to that given
func (o *ListArtifactsOfProjectBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the list artifacts of project bad request response
func (o *ListArtifactsOfProjectBadRequest) Code() int {
	return 400
}

func (o *ListArtifactsOfProjectBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects/{project_name_or_id}/artifacts][%d] listArtifactsOfProjectBadRequest %s", 400, payload)
}

func (o *ListArtifactsOfProjectBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects/{project_name_or_id}/artifacts][%d] listArtifactsOfProjectBadRequest %s", 400, payload)
}

func (o *ListArtifactsOfProjectBadRequest) GetPayload() *models.Errors {
	return o.Payload
}

func (o *ListArtifactsOfProjectBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListArtifactsOfProjectUnauthorized creates a ListArtifactsOfProjectUnauthorized with default headers values
func NewListArtifactsOfProjectUnauthorized() *ListArtifactsOfProjectUnauthorized {
	return &ListArtifactsOfProjectUnauthorized{}
}

/*
ListArtifactsOfProjectUnauthorized describes a response with status code 401, with default header values.

Unauthorized. Authentication is required to access this resource.
*/
type ListArtifactsOfProjectUnauthorized struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this list artifacts of project unauthorized response has a 2xx status code
func (o *ListArtifactsOfProjectUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list artifacts of project unauthorized response has a 3xx status code
func (o *ListArtifactsOfProjectUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list artifacts of project unauthorized response has a 4xx status code
func (o *ListArtifactsOfProjectUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this list artifacts of project unauthorized response has a 5xx status code
func (o *ListArtifactsOfProjectUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this list artifacts of project unauthorized response a status code equal to that given
func (o *ListArtifactsOfProjectUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the list artifacts of project unauthorized response
func (o *ListArtifactsOfProjectUnauthorized) Code() int {
	return 401
}

func (o *ListArtifactsOfProjectUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects/{project_name_or_id}/artifacts][%d] listArtifactsOfProjectUnauthorized %s", 401, payload)
}

func (o *ListArtifactsOfProjectUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects/{project_name_or_id}/artifacts][%d] listArtifactsOfProjectUnauthorized %s", 401, payload)
}

func (o *ListArtifactsOfProjectUnauthorized) GetPayload() *models.Errors {
	return o.Payload
}

func (o *ListArtifactsOfProjectUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListArtifactsOfProjectForbidden creates a ListArtifactsOfProjectForbidden with default headers values
func NewListArtifactsOfProjectForbidden() *ListArtifactsOfProjectForbidden {
	return &ListArtifactsOfProjectForbidden{}
}

/*
ListArtifactsOfProjectForbidden describes a response with status code 403, with default header values.

Forbidden. The caller does not have sufficient permission to perform the requested operation.
*/
type ListArtifactsOfProjectForbidden struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this list artifacts of project forbidden response has a 2xx status code
func (o *ListArtifactsOfProjectForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list artifacts of project forbidden response has a 3xx status code
func (o *ListArtifactsOfProjectForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list artifacts of project forbidden response has a 4xx status code
func (o *ListArtifactsOfProjectForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this list artifacts of project forbidden response has a 5xx status code
func (o *ListArtifactsOfProjectForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this list artifacts of project forbidden response a status code equal to that given
func (o *ListArtifactsOfProjectForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the list artifacts of project forbidden response
func (o *ListArtifactsOfProjectForbidden) Code() int {
	return 403
}

func (o *ListArtifactsOfProjectForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects/{project_name_or_id}/artifacts][%d] listArtifactsOfProjectForbidden %s", 403, payload)
}

func (o *ListArtifactsOfProjectForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects/{project_name_or_id}/artifacts][%d] listArtifactsOfProjectForbidden %s", 403, payload)
}

func (o *ListArtifactsOfProjectForbidden) GetPayload() *models.Errors {
	return o.Payload
}

func (o *ListArtifactsOfProjectForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListArtifactsOfProjectNotFound creates a ListArtifactsOfProjectNotFound with default headers values
func NewListArtifactsOfProjectNotFound() *ListArtifactsOfProjectNotFound {
	return &ListArtifactsOfProjectNotFound{}
}

/*
ListArtifactsOfProjectNotFound describes a response with status code 404, with default header values.

Not found. The requested resource does not exist.
*/
type ListArtifactsOfProjectNotFound struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this list artifacts of project not found response has a 2xx status code
func (o *ListArtifactsOfProjectNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list artifacts of project not found response has a 3xx status code
func (o *ListArtifactsOfProjectNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list artifacts of project not found response has a 4xx status code
func (o *ListArtifactsOfProjectNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this list artifacts of project not found response has a 5xx status code
func (o *ListArtifactsOfProjectNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this list artifacts of project not found response a status code equal to that given
func (o *ListArtifactsOfProjectNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the list artifacts of project not found response
func (o *ListArtifactsOfProjectNotFound) Code() int {
	return 404
}

func (o *ListArtifactsOfProjectNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects/{project_name_or_id}/artifacts][%d] listArtifactsOfProjectNotFound %s", 404, payload)
}

func (o *ListArtifactsOfProjectNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects/{project_name_or_id}/artifacts][%d] listArtifactsOfProjectNotFound %s", 404, payload)
}

func (o *ListArtifactsOfProjectNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *ListArtifactsOfProjectNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListArtifactsOfProjectUnprocessableEntity creates a ListArtifactsOfProjectUnprocessableEntity with default headers values
func NewListArtifactsOfProjectUnprocessableEntity() *ListArtifactsOfProjectUnprocessableEntity {
	return &ListArtifactsOfProjectUnprocessableEntity{}
}

/*
ListArtifactsOfProjectUnprocessableEntity describes a response with status code 422, with default header values.

Unsupported type. The resource or its properties are not supported by the requested operation.
*/
type ListArtifactsOfProjectUnprocessableEntity struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this list artifacts of project unprocessable entity response has a 2xx status code
func (o *ListArtifactsOfProjectUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list artifacts of project unprocessable entity response has a 3xx status code
func (o *ListArtifactsOfProjectUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list artifacts of project unprocessable entity response has a 4xx status code
func (o *ListArtifactsOfProjectUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this list artifacts of project unprocessable entity response has a 5xx status code
func (o *ListArtifactsOfProjectUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this list artifacts of project unprocessable entity response a status code equal to that given
func (o *ListArtifactsOfProjectUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the list artifacts of project unprocessable entity response
func (o *ListArtifactsOfProjectUnprocessableEntity) Code() int {
	return 422
}

func (o *ListArtifactsOfProjectUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects/{project_name_or_id}/artifacts][%d] listArtifactsOfProjectUnprocessableEntity %s", 422, payload)
}

func (o *ListArtifactsOfProjectUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects/{project_name_or_id}/artifacts][%d] listArtifactsOfProjectUnprocessableEntity %s", 422, payload)
}

func (o *ListArtifactsOfProjectUnprocessableEntity) GetPayload() *models.Errors {
	return o.Payload
}

func (o *ListArtifactsOfProjectUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListArtifactsOfProjectInternalServerError creates a ListArtifactsOfProjectInternalServerError with default headers values
func NewListArtifactsOfProjectInternalServerError() *ListArtifactsOfProjectInternalServerError {
	return &ListArtifactsOfProjectInternalServerError{}
}

/*
ListArtifactsOfProjectInternalServerError describes a response with status code 500, with default header values.

Internal server error. Inspect the `errors` array in the response body for details.
*/
type ListArtifactsOfProjectInternalServerError struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this list artifacts of project internal server error response has a 2xx status code
func (o *ListArtifactsOfProjectInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list artifacts of project internal server error response has a 3xx status code
func (o *ListArtifactsOfProjectInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list artifacts of project internal server error response has a 4xx status code
func (o *ListArtifactsOfProjectInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list artifacts of project internal server error response has a 5xx status code
func (o *ListArtifactsOfProjectInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list artifacts of project internal server error response a status code equal to that given
func (o *ListArtifactsOfProjectInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list artifacts of project internal server error response
func (o *ListArtifactsOfProjectInternalServerError) Code() int {
	return 500
}

func (o *ListArtifactsOfProjectInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects/{project_name_or_id}/artifacts][%d] listArtifactsOfProjectInternalServerError %s", 500, payload)
}

func (o *ListArtifactsOfProjectInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /projects/{project_name_or_id}/artifacts][%d] listArtifactsOfProjectInternalServerError %s", 500, payload)
}

func (o *ListArtifactsOfProjectInternalServerError) GetPayload() *models.Errors {
	return o.Payload
}

func (o *ListArtifactsOfProjectInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
