// Code generated by go-swagger; DO NOT EDIT.

package webhookjob

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

//go:generate mockery --name API --keeptree --with-expecter --case underscore

// API is the interface of the webhookjob client.
type API interface {
	/*
	   ListWebhookJobs lists project webhook jobs

	   This endpoint returns webhook jobs of a project.
	*/
	ListWebhookJobs(ctx context.Context, params *ListWebhookJobsParams) (*ListWebhookJobsOK, error)
}

// New creates a new webhookjob API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for webhookjob API
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
ListWebhookJobs lists project webhook jobs.

This endpoint returns webhook jobs of a project.
.
*/
func (a *Client) ListWebhookJobs(ctx context.Context, params *ListWebhookJobsParams) (*ListWebhookJobsOK, error) {
	result, err := a.transport.SubmitContext(ctx, &runtime.ClientOperation{
		ID:                 "ListWebhookJobs",
		Method:             "GET",
		PathPattern:        "/projects/{project_name_or_id}/webhook/jobs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListWebhookJobsReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}

	switch value := result.(type) {
	case *ListWebhookJobsOK:
		return value, nil
	case *ListWebhookJobsBadRequest:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *ListWebhookJobsUnauthorized:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *ListWebhookJobsForbidden:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *ListWebhookJobsInternalServerError:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	}

	// unexpected response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown responses return an error above: so this is a codegen issue.
	msg := fmt.Sprintf("unexpected success response for ListWebhookJobs: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [WebhookjobParams].
	ctx context.Context
}
