// Code generated by go-swagger; DO NOT EDIT.

package oidc

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

//go:generate mockery --name API --keeptree --with-expecter --case underscore

// API is the interface of the oidc client.
type API interface {
	/*
	   PingOIDC tests the OIDC endpoint

	   Test the OIDC endpoint, the setting of the endpoint is provided in the request.  This API can only be called by system admin.
	*/
	PingOIDC(ctx context.Context, params *PingOIDCParams) (*PingOIDCOK, error)
}

// New creates a new oidc API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for oidc API
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
PingOIDC tests the OIDC endpoint.

Test the OIDC endpoint, the setting of the endpoint is provided in the request.  This API can only be called by system admin.
.
*/
func (a *Client) PingOIDC(ctx context.Context, params *PingOIDCParams) (*PingOIDCOK, error) {
	result, err := a.transport.SubmitContext(ctx, &runtime.ClientOperation{
		ID:                 "pingOIDC",
		Method:             "POST",
		PathPattern:        "/system/oidc/ping",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PingOIDCReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}

	switch value := result.(type) {
	case *PingOIDCOK:
		return value, nil
	case *PingOIDCBadRequest:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *PingOIDCUnauthorized:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *PingOIDCForbidden:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *PingOIDCInternalServerError:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	}

	// unexpected response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown responses return an error above: so this is a codegen issue.
	msg := fmt.Sprintf("unexpected success response for pingOIDC: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [OIDCParams].
	ctx context.Context
}
