// Code generated by go-swagger; DO NOT EDIT.

package immutable

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/goharbor/go-client/pkg/sdk/v2.0/models"
)

// UpdateImmuRuleReader is a Reader for the UpdateImmuRule structure.
type UpdateImmuRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateImmuRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateImmuRuleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateImmuRuleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateImmuRuleUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateImmuRuleForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateImmuRuleNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateImmuRuleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /projects/{project_name_or_id}/immutabletagrules/{immutable_rule_id}] UpdateImmuRule", response, response.Code())
	}
}

// NewUpdateImmuRuleOK creates a UpdateImmuRuleOK with default headers values
func NewUpdateImmuRuleOK() *UpdateImmuRuleOK {
	return &UpdateImmuRuleOK{}
}

/*
UpdateImmuRuleOK describes a response with status code 200, with default header values.

Success
*/
type UpdateImmuRuleOK struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string
}

// IsSuccess returns true when this update immu rule o k response has a 2xx status code
func (o *UpdateImmuRuleOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update immu rule o k response has a 3xx status code
func (o *UpdateImmuRuleOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update immu rule o k response has a 4xx status code
func (o *UpdateImmuRuleOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update immu rule o k response has a 5xx status code
func (o *UpdateImmuRuleOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update immu rule o k response a status code equal to that given
func (o *UpdateImmuRuleOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update immu rule o k response
func (o *UpdateImmuRuleOK) Code() int {
	return 200
}

func (o *UpdateImmuRuleOK) Error() string {
	return fmt.Sprintf("[PUT /projects/{project_name_or_id}/immutabletagrules/{immutable_rule_id}][%d] updateImmuRuleOK", 200)
}

func (o *UpdateImmuRuleOK) String() string {
	return fmt.Sprintf("[PUT /projects/{project_name_or_id}/immutabletagrules/{immutable_rule_id}][%d] updateImmuRuleOK", 200)
}

func (o *UpdateImmuRuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	return nil
}

// NewUpdateImmuRuleBadRequest creates a UpdateImmuRuleBadRequest with default headers values
func NewUpdateImmuRuleBadRequest() *UpdateImmuRuleBadRequest {
	return &UpdateImmuRuleBadRequest{}
}

/*
UpdateImmuRuleBadRequest describes a response with status code 400, with default header values.

Bad request. The request body or query parameters are invalid. Inspect the `errors` array in the response body for details.
*/
type UpdateImmuRuleBadRequest struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this update immu rule bad request response has a 2xx status code
func (o *UpdateImmuRuleBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update immu rule bad request response has a 3xx status code
func (o *UpdateImmuRuleBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update immu rule bad request response has a 4xx status code
func (o *UpdateImmuRuleBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update immu rule bad request response has a 5xx status code
func (o *UpdateImmuRuleBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update immu rule bad request response a status code equal to that given
func (o *UpdateImmuRuleBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the update immu rule bad request response
func (o *UpdateImmuRuleBadRequest) Code() int {
	return 400
}

func (o *UpdateImmuRuleBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /projects/{project_name_or_id}/immutabletagrules/{immutable_rule_id}][%d] updateImmuRuleBadRequest %s", 400, payload)
}

func (o *UpdateImmuRuleBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /projects/{project_name_or_id}/immutabletagrules/{immutable_rule_id}][%d] updateImmuRuleBadRequest %s", 400, payload)
}

func (o *UpdateImmuRuleBadRequest) GetPayload() *models.Errors {
	return o.Payload
}

func (o *UpdateImmuRuleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateImmuRuleUnauthorized creates a UpdateImmuRuleUnauthorized with default headers values
func NewUpdateImmuRuleUnauthorized() *UpdateImmuRuleUnauthorized {
	return &UpdateImmuRuleUnauthorized{}
}

/*
UpdateImmuRuleUnauthorized describes a response with status code 401, with default header values.

Unauthorized. Authentication is required to access this resource.
*/
type UpdateImmuRuleUnauthorized struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this update immu rule unauthorized response has a 2xx status code
func (o *UpdateImmuRuleUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update immu rule unauthorized response has a 3xx status code
func (o *UpdateImmuRuleUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update immu rule unauthorized response has a 4xx status code
func (o *UpdateImmuRuleUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this update immu rule unauthorized response has a 5xx status code
func (o *UpdateImmuRuleUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this update immu rule unauthorized response a status code equal to that given
func (o *UpdateImmuRuleUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the update immu rule unauthorized response
func (o *UpdateImmuRuleUnauthorized) Code() int {
	return 401
}

func (o *UpdateImmuRuleUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /projects/{project_name_or_id}/immutabletagrules/{immutable_rule_id}][%d] updateImmuRuleUnauthorized %s", 401, payload)
}

func (o *UpdateImmuRuleUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /projects/{project_name_or_id}/immutabletagrules/{immutable_rule_id}][%d] updateImmuRuleUnauthorized %s", 401, payload)
}

func (o *UpdateImmuRuleUnauthorized) GetPayload() *models.Errors {
	return o.Payload
}

func (o *UpdateImmuRuleUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateImmuRuleForbidden creates a UpdateImmuRuleForbidden with default headers values
func NewUpdateImmuRuleForbidden() *UpdateImmuRuleForbidden {
	return &UpdateImmuRuleForbidden{}
}

/*
UpdateImmuRuleForbidden describes a response with status code 403, with default header values.

Forbidden. The caller does not have sufficient permission to perform the requested operation.
*/
type UpdateImmuRuleForbidden struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this update immu rule forbidden response has a 2xx status code
func (o *UpdateImmuRuleForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update immu rule forbidden response has a 3xx status code
func (o *UpdateImmuRuleForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update immu rule forbidden response has a 4xx status code
func (o *UpdateImmuRuleForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this update immu rule forbidden response has a 5xx status code
func (o *UpdateImmuRuleForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this update immu rule forbidden response a status code equal to that given
func (o *UpdateImmuRuleForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the update immu rule forbidden response
func (o *UpdateImmuRuleForbidden) Code() int {
	return 403
}

func (o *UpdateImmuRuleForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /projects/{project_name_or_id}/immutabletagrules/{immutable_rule_id}][%d] updateImmuRuleForbidden %s", 403, payload)
}

func (o *UpdateImmuRuleForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /projects/{project_name_or_id}/immutabletagrules/{immutable_rule_id}][%d] updateImmuRuleForbidden %s", 403, payload)
}

func (o *UpdateImmuRuleForbidden) GetPayload() *models.Errors {
	return o.Payload
}

func (o *UpdateImmuRuleForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateImmuRuleNotFound creates a UpdateImmuRuleNotFound with default headers values
func NewUpdateImmuRuleNotFound() *UpdateImmuRuleNotFound {
	return &UpdateImmuRuleNotFound{}
}

/*
UpdateImmuRuleNotFound describes a response with status code 404, with default header values.

Not found. The requested resource does not exist.
*/
type UpdateImmuRuleNotFound struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this update immu rule not found response has a 2xx status code
func (o *UpdateImmuRuleNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update immu rule not found response has a 3xx status code
func (o *UpdateImmuRuleNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update immu rule not found response has a 4xx status code
func (o *UpdateImmuRuleNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update immu rule not found response has a 5xx status code
func (o *UpdateImmuRuleNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update immu rule not found response a status code equal to that given
func (o *UpdateImmuRuleNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the update immu rule not found response
func (o *UpdateImmuRuleNotFound) Code() int {
	return 404
}

func (o *UpdateImmuRuleNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /projects/{project_name_or_id}/immutabletagrules/{immutable_rule_id}][%d] updateImmuRuleNotFound %s", 404, payload)
}

func (o *UpdateImmuRuleNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /projects/{project_name_or_id}/immutabletagrules/{immutable_rule_id}][%d] updateImmuRuleNotFound %s", 404, payload)
}

func (o *UpdateImmuRuleNotFound) GetPayload() *models.Errors {
	return o.Payload
}

func (o *UpdateImmuRuleNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateImmuRuleInternalServerError creates a UpdateImmuRuleInternalServerError with default headers values
func NewUpdateImmuRuleInternalServerError() *UpdateImmuRuleInternalServerError {
	return &UpdateImmuRuleInternalServerError{}
}

/*
UpdateImmuRuleInternalServerError describes a response with status code 500, with default header values.

Internal server error. Inspect the `errors` array in the response body for details.
*/
type UpdateImmuRuleInternalServerError struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this update immu rule internal server error response has a 2xx status code
func (o *UpdateImmuRuleInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update immu rule internal server error response has a 3xx status code
func (o *UpdateImmuRuleInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update immu rule internal server error response has a 4xx status code
func (o *UpdateImmuRuleInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this update immu rule internal server error response has a 5xx status code
func (o *UpdateImmuRuleInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this update immu rule internal server error response a status code equal to that given
func (o *UpdateImmuRuleInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the update immu rule internal server error response
func (o *UpdateImmuRuleInternalServerError) Code() int {
	return 500
}

func (o *UpdateImmuRuleInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /projects/{project_name_or_id}/immutabletagrules/{immutable_rule_id}][%d] updateImmuRuleInternalServerError %s", 500, payload)
}

func (o *UpdateImmuRuleInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /projects/{project_name_or_id}/immutabletagrules/{immutable_rule_id}][%d] updateImmuRuleInternalServerError %s", 500, payload)
}

func (o *UpdateImmuRuleInternalServerError) GetPayload() *models.Errors {
	return o.Payload
}

func (o *UpdateImmuRuleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
