// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// AdditionLink addition link
//
// swagger:model AdditionLink
type AdditionLink struct {

	// Determine whether the link is an absolute URL or not
	Absolute bool `json:"absolute"`

	// The link of the addition
	Href string `json:"href,omitempty"`
}

// Validate validates this addition link
func (m *AdditionLink) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this addition link based on context it is used
func (m *AdditionLink) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AdditionLink) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AdditionLink) UnmarshalBinary(b []byte) error {
	var res AdditionLink
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
