// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// BoolConfigItem bool config item
//
// swagger:model BoolConfigItem
type BoolConfigItem struct {

	// The configure item can be updated or not
	Editable bool `json:"editable"`

	// The boolean value of current config item
	Value bool `json:"value"`
}

// Validate validates this bool config item
func (m *BoolConfigItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this bool config item based on context it is used
func (m *BoolConfigItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BoolConfigItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BoolConfigItem) UnmarshalBinary(b []byte) error {
	var res BoolConfigItem
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
