// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// FilterStyle The style of the resource filter
//
// swagger:model FilterStyle
type FilterStyle struct {

	// The filter style
	Style string `json:"style,omitempty"`

	// The filter type
	Type string `json:"type,omitempty"`

	// The filter values
	Values []string `json:"values"`
}

// Validate validates this filter style
func (m *FilterStyle) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this filter style based on context it is used
func (m *FilterStyle) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FilterStyle) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FilterStyle) UnmarshalBinary(b []byte) error {
	var res FilterStyle
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
