// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// GCHistory GC history
//
// swagger:model GCHistory
type GCHistory struct {

	// the creation time of gc job.
	// Format: date-time
	CreationTime strfmt.DateTime `json:"creation_time,omitempty"`

	// if gc job was deleted.
	Deleted bool `json:"deleted,omitempty"`

	// the id of gc job.
	ID int64 `json:"id,omitempty"`

	// the job kind of gc job.
	JobKind string `json:"job_kind,omitempty"`

	// the job name of gc job.
	JobName string `json:"job_name,omitempty"`

	// the job parameters of gc job.
	JobParameters string `json:"job_parameters,omitempty"`

	// the status of gc job.
	JobStatus string `json:"job_status,omitempty"`

	// schedule
	Schedule *ScheduleObj `json:"schedule,omitempty"`

	// the update time of gc job.
	// Format: date-time
	UpdateTime strfmt.DateTime `json:"update_time,omitempty"`
}

// Validate validates this GC history
func (m *GCHistory) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreationTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSchedule(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdateTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GCHistory) validateCreationTime(formats strfmt.Registry) error {
	if typeutils.IsZero(m.CreationTime) { // not required
		return nil
	}

	if err := validate.FormatOf("creation_time", "body", "date-time", m.CreationTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *GCHistory) validateSchedule(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Schedule) { // not required
		return nil
	}

	if m.Schedule != nil {
		if err := m.Schedule.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("schedule")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("schedule")
			}

			return err
		}
	}

	return nil
}

func (m *GCHistory) validateUpdateTime(formats strfmt.Registry) error {
	if typeutils.IsZero(m.UpdateTime) { // not required
		return nil
	}

	if err := validate.FormatOf("update_time", "body", "date-time", m.UpdateTime.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this GC history based on the context it is used
func (m *GCHistory) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSchedule(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GCHistory) contextValidateSchedule(ctx context.Context, formats strfmt.Registry) error {

	if m.Schedule != nil {

		if typeutils.IsZero(m.Schedule) { // not required
			return nil
		}

		if err := m.Schedule.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("schedule")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("schedule")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GCHistory) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GCHistory) UnmarshalBinary(b []byte) error {
	var res GCHistory
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
