// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// Icon icon
//
// swagger:model Icon
type Icon struct {

	// The base64 encoded content of the icon
	Content string `json:"content,omitempty"`

	// The content type of the icon
	ContentType string `json:"content-type,omitempty"`
}

// Validate validates this icon
func (m *Icon) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this icon based on context it is used
func (m *Icon) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Icon) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Icon) UnmarshalBinary(b []byte) error {
	var res Icon
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
