// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// NotifyType Webhook supported notify type.
// Example: http
//
// swagger:model NotifyType
type NotifyType string

// Validate validates this notify type
func (m NotifyType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this notify type based on context it is used
func (m NotifyType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
