// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// RetentionRuleTrigger retention rule trigger
//
// swagger:model RetentionRuleTrigger
type RetentionRuleTrigger struct {

	// kind
	Kind string `json:"kind,omitempty"`

	// references
	References any `json:"references,omitempty"`

	// settings
	Settings any `json:"settings,omitempty"`
}

// Validate validates this retention rule trigger
func (m *RetentionRuleTrigger) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this retention rule trigger based on context it is used
func (m *RetentionRuleTrigger) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RetentionRuleTrigger) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RetentionRuleTrigger) UnmarshalBinary(b []byte) error {
	var res RetentionRuleTrigger
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
