// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// RetentionSelectorMetadata retention selector
//
// swagger:model RetentionSelectorMetadata
type RetentionSelectorMetadata struct {

	// decorations
	Decorations []string `json:"decorations"`

	// display text
	DisplayText string `json:"display_text,omitempty"`

	// kind
	Kind string `json:"kind,omitempty"`
}

// Validate validates this retention selector metadata
func (m *RetentionSelectorMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this retention selector metadata based on context it is used
func (m *RetentionSelectorMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RetentionSelectorMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RetentionSelectorMetadata) UnmarshalBinary(b []byte) error {
	var res RetentionSelectorMetadata
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
