// Code generated by go-swagger; DO NOT EDIT.

package auditlog

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/goharbor/go-client/pkg/sdk/v2.0/models"
)

// ListAuditLogEventTypesReader is a Reader for the ListAuditLogEventTypes structure.
type ListAuditLogEventTypesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAuditLogEventTypesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListAuditLogEventTypesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListAuditLogEventTypesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListAuditLogEventTypesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListAuditLogEventTypesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /auditlog-exts/events] listAuditLogEventTypes", response, response.Code())
	}
}

// NewListAuditLogEventTypesOK creates a ListAuditLogEventTypesOK with default headers values
func NewListAuditLogEventTypesOK() *ListAuditLogEventTypesOK {
	return &ListAuditLogEventTypesOK{}
}

/*
ListAuditLogEventTypesOK describes a response with status code 200, with default header values.

Success
*/
type ListAuditLogEventTypesOK struct {
	Payload []*models.AuditLogEventType
}

// IsSuccess returns true when this list audit log event types o k response has a 2xx status code
func (o *ListAuditLogEventTypesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list audit log event types o k response has a 3xx status code
func (o *ListAuditLogEventTypesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list audit log event types o k response has a 4xx status code
func (o *ListAuditLogEventTypesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list audit log event types o k response has a 5xx status code
func (o *ListAuditLogEventTypesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list audit log event types o k response a status code equal to that given
func (o *ListAuditLogEventTypesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list audit log event types o k response
func (o *ListAuditLogEventTypesOK) Code() int {
	return 200
}

func (o *ListAuditLogEventTypesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auditlog-exts/events][%d] listAuditLogEventTypesOK %s", 200, payload)
}

func (o *ListAuditLogEventTypesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auditlog-exts/events][%d] listAuditLogEventTypesOK %s", 200, payload)
}

func (o *ListAuditLogEventTypesOK) GetPayload() []*models.AuditLogEventType {
	return o.Payload
}

func (o *ListAuditLogEventTypesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListAuditLogEventTypesUnauthorized creates a ListAuditLogEventTypesUnauthorized with default headers values
func NewListAuditLogEventTypesUnauthorized() *ListAuditLogEventTypesUnauthorized {
	return &ListAuditLogEventTypesUnauthorized{}
}

/*
ListAuditLogEventTypesUnauthorized describes a response with status code 401, with default header values.

Unauthorized. Authentication is required to access this resource.
*/
type ListAuditLogEventTypesUnauthorized struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this list audit log event types unauthorized response has a 2xx status code
func (o *ListAuditLogEventTypesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list audit log event types unauthorized response has a 3xx status code
func (o *ListAuditLogEventTypesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list audit log event types unauthorized response has a 4xx status code
func (o *ListAuditLogEventTypesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this list audit log event types unauthorized response has a 5xx status code
func (o *ListAuditLogEventTypesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this list audit log event types unauthorized response a status code equal to that given
func (o *ListAuditLogEventTypesUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the list audit log event types unauthorized response
func (o *ListAuditLogEventTypesUnauthorized) Code() int {
	return 401
}

func (o *ListAuditLogEventTypesUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auditlog-exts/events][%d] listAuditLogEventTypesUnauthorized %s", 401, payload)
}

func (o *ListAuditLogEventTypesUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auditlog-exts/events][%d] listAuditLogEventTypesUnauthorized %s", 401, payload)
}

func (o *ListAuditLogEventTypesUnauthorized) GetPayload() *models.Errors {
	return o.Payload
}

func (o *ListAuditLogEventTypesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListAuditLogEventTypesForbidden creates a ListAuditLogEventTypesForbidden with default headers values
func NewListAuditLogEventTypesForbidden() *ListAuditLogEventTypesForbidden {
	return &ListAuditLogEventTypesForbidden{}
}

/*
ListAuditLogEventTypesForbidden describes a response with status code 403, with default header values.

Forbidden. The caller does not have sufficient permission to perform the requested operation.
*/
type ListAuditLogEventTypesForbidden struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this list audit log event types forbidden response has a 2xx status code
func (o *ListAuditLogEventTypesForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list audit log event types forbidden response has a 3xx status code
func (o *ListAuditLogEventTypesForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list audit log event types forbidden response has a 4xx status code
func (o *ListAuditLogEventTypesForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this list audit log event types forbidden response has a 5xx status code
func (o *ListAuditLogEventTypesForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this list audit log event types forbidden response a status code equal to that given
func (o *ListAuditLogEventTypesForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the list audit log event types forbidden response
func (o *ListAuditLogEventTypesForbidden) Code() int {
	return 403
}

func (o *ListAuditLogEventTypesForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auditlog-exts/events][%d] listAuditLogEventTypesForbidden %s", 403, payload)
}

func (o *ListAuditLogEventTypesForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auditlog-exts/events][%d] listAuditLogEventTypesForbidden %s", 403, payload)
}

func (o *ListAuditLogEventTypesForbidden) GetPayload() *models.Errors {
	return o.Payload
}

func (o *ListAuditLogEventTypesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListAuditLogEventTypesInternalServerError creates a ListAuditLogEventTypesInternalServerError with default headers values
func NewListAuditLogEventTypesInternalServerError() *ListAuditLogEventTypesInternalServerError {
	return &ListAuditLogEventTypesInternalServerError{}
}

/*
ListAuditLogEventTypesInternalServerError describes a response with status code 500, with default header values.

Internal server error. Inspect the `errors` array in the response body for details.
*/
type ListAuditLogEventTypesInternalServerError struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this list audit log event types internal server error response has a 2xx status code
func (o *ListAuditLogEventTypesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list audit log event types internal server error response has a 3xx status code
func (o *ListAuditLogEventTypesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list audit log event types internal server error response has a 4xx status code
func (o *ListAuditLogEventTypesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list audit log event types internal server error response has a 5xx status code
func (o *ListAuditLogEventTypesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list audit log event types internal server error response a status code equal to that given
func (o *ListAuditLogEventTypesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list audit log event types internal server error response
func (o *ListAuditLogEventTypesInternalServerError) Code() int {
	return 500
}

func (o *ListAuditLogEventTypesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auditlog-exts/events][%d] listAuditLogEventTypesInternalServerError %s", 500, payload)
}

func (o *ListAuditLogEventTypesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auditlog-exts/events][%d] listAuditLogEventTypesInternalServerError %s", 500, payload)
}

func (o *ListAuditLogEventTypesInternalServerError) GetPayload() *models.Errors {
	return o.Payload
}

func (o *ListAuditLogEventTypesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
