// Code generated by go-swagger; DO NOT EDIT.

package health

import (
	"context"
	"fmt"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

//go:generate mockery --name API --keeptree --with-expecter --case underscore

// API is the interface of the health client.
type API interface {
	/*
	   GetHealth checks the status of harbor components

	   Check the status of Harbor components. This path does not require authentication.*/
	GetHealth(ctx context.Context, params *GetHealthParams) (*GetHealthOK, error)
}

// New creates a new health API client.
func New(transport runtime.ContextualTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for health API
*/
type Client struct {
	transport runtime.ContextualTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
GetHealth checks the status of harbor components.

Check the status of Harbor components. This path does not require authentication..
*/
func (a *Client) GetHealth(ctx context.Context, params *GetHealthParams) (*GetHealthOK, error) {
	result, err := a.transport.SubmitContext(ctx, &runtime.ClientOperation{
		ID:                 "getHealth",
		Method:             "GET",
		PathPattern:        "/health",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetHealthReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}

	switch value := result.(type) {
	case *GetHealthOK:
		return value, nil
	case *GetHealthInternalServerError:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	}

	// unexpected response.

	// no default response is defined.
	//
	// safeguard: normally, in the absence of a default response, unknown responses return an error above: so this is a codegen issue.
	msg := fmt.Sprintf("unexpected success response for getHealth: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// innerParams captures internal fields so they don't conflict with user-supplied parameters.
type innerParams struct {
	timeout time.Duration

	// Deprecated: use the operation call with context to pass the context instead of [HealthParams].
	ctx context.Context
}
