// Code generated by go-swagger; DO NOT EDIT.

package user

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/goharbor/go-client/pkg/sdk/v2.0/models"
)

// GetCurrentUserPermissionsReader is a Reader for the GetCurrentUserPermissions structure.
type GetCurrentUserPermissionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCurrentUserPermissionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetCurrentUserPermissionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetCurrentUserPermissionsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /users/current/permissions] getCurrentUserPermissions", response, response.Code())
	}
}

// NewGetCurrentUserPermissionsOK creates a GetCurrentUserPermissionsOK with default headers values
func NewGetCurrentUserPermissionsOK() *GetCurrentUserPermissionsOK {
	return &GetCurrentUserPermissionsOK{}
}

/*
GetCurrentUserPermissionsOK describes a response with status code 200, with default header values.

Get current user permission successfully.
*/
type GetCurrentUserPermissionsOK struct {
	Payload []*models.Permission
}

// IsSuccess returns true when this get current user permissions o k response has a 2xx status code
func (o *GetCurrentUserPermissionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get current user permissions o k response has a 3xx status code
func (o *GetCurrentUserPermissionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get current user permissions o k response has a 4xx status code
func (o *GetCurrentUserPermissionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get current user permissions o k response has a 5xx status code
func (o *GetCurrentUserPermissionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get current user permissions o k response a status code equal to that given
func (o *GetCurrentUserPermissionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get current user permissions o k response
func (o *GetCurrentUserPermissionsOK) Code() int {
	return 200
}

func (o *GetCurrentUserPermissionsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/current/permissions][%d] getCurrentUserPermissionsOK %s", 200, payload)
}

func (o *GetCurrentUserPermissionsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/current/permissions][%d] getCurrentUserPermissionsOK %s", 200, payload)
}

func (o *GetCurrentUserPermissionsOK) GetPayload() []*models.Permission {
	return o.Payload
}

func (o *GetCurrentUserPermissionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetCurrentUserPermissionsUnauthorized creates a GetCurrentUserPermissionsUnauthorized with default headers values
func NewGetCurrentUserPermissionsUnauthorized() *GetCurrentUserPermissionsUnauthorized {
	return &GetCurrentUserPermissionsUnauthorized{}
}

/*
GetCurrentUserPermissionsUnauthorized describes a response with status code 401, with default header values.

Unauthorized. Authentication is required to access this resource.
*/
type GetCurrentUserPermissionsUnauthorized struct {

	/* The ID of the corresponding request for the response
	 */
	XRequestID string

	Payload *models.Errors
}

// IsSuccess returns true when this get current user permissions unauthorized response has a 2xx status code
func (o *GetCurrentUserPermissionsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get current user permissions unauthorized response has a 3xx status code
func (o *GetCurrentUserPermissionsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get current user permissions unauthorized response has a 4xx status code
func (o *GetCurrentUserPermissionsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get current user permissions unauthorized response has a 5xx status code
func (o *GetCurrentUserPermissionsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get current user permissions unauthorized response a status code equal to that given
func (o *GetCurrentUserPermissionsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get current user permissions unauthorized response
func (o *GetCurrentUserPermissionsUnauthorized) Code() int {
	return 401
}

func (o *GetCurrentUserPermissionsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/current/permissions][%d] getCurrentUserPermissionsUnauthorized %s", 401, payload)
}

func (o *GetCurrentUserPermissionsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/current/permissions][%d] getCurrentUserPermissionsUnauthorized %s", 401, payload)
}

func (o *GetCurrentUserPermissionsUnauthorized) GetPayload() *models.Errors {
	return o.Payload
}

func (o *GetCurrentUserPermissionsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-Request-Id
	hdrXRequestID := response.GetHeader("X-Request-Id")

	if hdrXRequestID != "" {
		o.XRequestID = hdrXRequestID
	}

	o.Payload = new(models.Errors)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
